/** Maps language names to Monaco language identifiers */
export const languageMap: Record<string, string> = {
  swift: "swift",
  python: "python",
  typescript: "typescript",
  javascript: "javascript",
  ts: "typescript",
  js: "javascript",
  py: "python",
  java: "java",
  go: "go",
  rust: "rust",
  c: "c",
  cpp: "cpp",
  "c++": "cpp",
  csharp: "csharp",
  "c#": "csharp",
  ruby: "ruby",
  php: "php",
  html: "html",
  css: "css",
  json: "json",
  sql: "sql",
};
